name: Build Alpine Generic

on:
  workflow_dispatch:
  push:
    branches:
      - r9000-xr700-main
    paths:
      - 'package/kernel/**'
      - 'target/linux/alpine/**'
jobs:
  build:
    name: Build linux/alpine/generic
    uses: openwrt/actions-shared-workflows/.github/workflows/kernel.yml@main
    with:
      targets: linux/alpine/generic
permissions:
  contents: write
  packages: write
  actions: write
