name: Build Alpine Generic

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-alpine-generic.yml'
    branches:
      - r9000-xr700-main

permissions:
  contents: read

jobs:
  build:
    name: Build alpine/generic
    permissions:
      contents: read
      packages: read
    uses: openwrt/actions-shared-workflows/.github/workflows/build.yml@main
    with:
      targets: alpine/generic
