name: Build Alpine Generic

on:
  workflow_dispatch:
  push:
    paths:
      - 'package/kernel/*'
      - 'target/linux/alpine/*'
    branches:
      - r9000-xr700-main

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    paths-ignore:
      - 'package/lang/python/*'
    name: Build linux/alpine/generic
    uses: openwrt/actions-shared-workflows/.github/workflows/kernel.yml@main
